spring:
  application:
    name: ContactsManagement
  datasource:
    url: jdbc:mysql://localhost:3306/BDContacts?createDatabaseIfNotExist=true
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async: 
      request-timeout: 3600000
server:
  port: 8090
  
      
